name: testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  # This workflow contains a job called "integration"
  integration:
    # The runners that the job will run on
    runs-on: "ubuntu-latest"
    # A strategy that defines different variations of an environment to run each job in.
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm i
        if: always()
      - name: check eslint
        run: npm run lint:ts
        if: always()
      - name: check unit tests
        run: npm run unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        run: npm run test:ui
        if: always()
